---
driver:
  network:
  - ["private_network", {ip: "192.168.33.42"}]
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu/trusty64

suites:
  - name: smoslt_docker
    run_list:
    - recipe[df_box_smoslt::default]
    attributes:
